find_package(PkgConfig REQUIRED)
pkg_check_modules(LIBUSB REQUIRED libusb-1.0)

set(PLATFORM_LIBS SDL3::SDL3-static ${LIBUSB_LIBRARIES} ${ADDITIONAL_LIBS})
set(PLATFORM_LIBS_PATH ${LIBUSB_LIBRARY_DIRS})
set(PLATFORM_INCLUDES ${LIBUSB_INCLUDE_DIRS} vendor/SDL/include)