/* Autogenerated by hxtools bin2c */
#ifndef COMMANDDATA_LGX_H
#define COMMANDDATA_LGX_H 1

#include "config.h"
#include <string>

#ifdef GC550_SUPPORT

extern std::string lgx_setup_commands;

#endif

#endif /* COMMANDDATA_LGX_H */
