#include "sdl/SdlVideoOutput.h"
#include "sdl/SdlAudioOutput.h"
#include "usb/UsbStream.h"
#include "NullAudioOutput.h"
#include "NullVideoOutput.h"
#include "FakeUsbStream.h"
#include "SimpleErrorSink.h"